services:
  nginx:
    image: nginx
    volumes:
    - ./public:/usr/share/nginx/html:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - "80:80"
    environment:
    # - NGINX_HOST=foobar.com
    - NGINX_PORT=80
